// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/davidmm07/pressroom/internal/domain"
)

type Agent struct {
	ID          string     `json:"id"`
	Slug        string     `json:"slug"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Department  Department `json:"department"`
	// Department lead accountable for this agent's results.
	Owner string `json:"owner"`
	// The system prompt: the agent's job description.
	Instructions string  `json:"instructions"`
	Model        *Model  `json:"model"`
	Tools        []*Tool `json:"tools"`
	// Event types that start a run automatically, e.g. ticket.created.
	Triggers []string `json:"triggers"`
	Budget   *Budget  `json:"budget"`
	// Human minutes one accepted run replaces; turns runs into hours saved.
	MinutesSavedPerRun float64     `json:"minutesSavedPerRun"`
	Status             AgentStatus `json:"status"`
	// Pass back as `expectedVersion` when updating.
	Version          int            `json:"version"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	Scorecard        *Scorecard     `json:"scorecard"`
	Runs             *RunConnection `json:"runs"`
	ActiveExperiment *Experiment    `json:"activeExperiment,omitempty"`
	Evaluations      []*Evaluation  `json:"evaluations"`
}

type AgentPayload struct {
	Agent      *Agent       `json:"agent,omitempty"`
	UserErrors []*UserError `json:"userErrors"`
}

type Budget struct {
	MaxSteps int           `json:"maxSteps"`
	MaxCost  domain.Micros `json:"maxCost"`
}

type CreateAgentInput struct {
	Slug         string     `json:"slug"`
	Name         string     `json:"name"`
	Description  *string    `json:"description,omitempty"`
	Department   Department `json:"department"`
	Owner        string     `json:"owner"`
	Instructions string     `json:"instructions"`
	// provider/name, e.g. anthropic/claude-opus-5 or xai/grok-4
	Model              string        `json:"model"`
	Tools              []string      `json:"tools"`
	Triggers           []string      `json:"triggers,omitempty"`
	MaxSteps           int           `json:"maxSteps"`
	MaxCost            domain.Micros `json:"maxCost"`
	MinutesSavedPerRun float64       `json:"minutesSavedPerRun"`
}

type CrewSummary struct {
	ActiveAgents         int           `json:"activeAgents"`
	OnProbation          int           `json:"onProbation"`
	Retired              int           `json:"retired"`
	RunsLast7Days        int           `json:"runsLast7Days"`
	AwaitingApproval     int           `json:"awaitingApproval"`
	HoursSavedLast30Days float64       `json:"hoursSavedLast30Days"`
	SpendLast30Days      domain.Micros `json:"spendLast30Days"`
	NetValueLast30Days   domain.Micros `json:"netValueLast30Days"`
}

type EvaluateCrewPayload struct {
	Evaluations []*Evaluation `json:"evaluations"`
	UserErrors  []*UserError  `json:"userErrors"`
}

type Evaluation struct {
	ID           string      `json:"id"`
	AgentID      string      `json:"agentId"`
	Agent        *Agent      `json:"agent"`
	Decision     Decision    `json:"decision"`
	Reason       string      `json:"reason"`
	StatusBefore AgentStatus `json:"statusBefore"`
	StatusAfter  AgentStatus `json:"statusAfter"`
	Scorecard    *Scorecard  `json:"scorecard"`
	CreatedAt    time.Time   `json:"createdAt"`
}

type Experiment struct {
	ID                  string           `json:"id"`
	AgentID             string           `json:"agentId"`
	Agent               *Agent           `json:"agent"`
	Champion            *Model           `json:"champion"`
	Challenger          *Model           `json:"challenger"`
	TrafficPercent      int              `json:"trafficPercent"`
	Hypothesis          string           `json:"hypothesis"`
	Status              ExperimentStatus `json:"status"`
	Outcome             string           `json:"outcome"`
	CreatedAt           time.Time        `json:"createdAt"`
	ConcludedAt         *time.Time       `json:"concludedAt,omitempty"`
	ChampionScorecard   *Scorecard       `json:"championScorecard"`
	ChallengerScorecard *Scorecard       `json:"challengerScorecard"`
}

type ExperimentPayload struct {
	Experiment *Experiment  `json:"experiment,omitempty"`
	UserErrors []*UserError `json:"userErrors"`
}

type Model struct {
	// provider/name, e.g. anthropic/claude-opus-5
	ID       string        `json:"id"`
	Provider ModelProvider `json:"provider"`
	Name     string        `json:"name"`
}

type ModelOption struct {
	Model *Model `json:"model"`
	Label string `json:"label"`
	// List price in USD per million input tokens.
	InputPerMTok float64 `json:"inputPerMTok"`
	// List price in USD per million output tokens.
	OutputPerMTok float64 `json:"outputPerMTok"`
	// Credentials are configured, or the sandbox will serve it.
	Available bool `json:"available"`
}

type Mutation struct {
}

type Opportunity struct {
	ID              string            `json:"id"`
	Title           string            `json:"title"`
	Problem         string            `json:"problem"`
	Department      Department        `json:"department"`
	SubmittedBy     string            `json:"submittedBy"`
	WeeklyVolume    int               `json:"weeklyVolume"`
	MinutesPerTask  float64           `json:"minutesPerTask"`
	DataSensitivity Level             `json:"dataSensitivity"`
	ErrorCost       Level             `json:"errorCost"`
	Status          OpportunityStatus `json:"status"`
	// Human hours per week the task takes today.
	HoursPerWeek float64 `json:"hoursPerWeek"`
	// 0.3 to 1: discount for sensitive data and costly mistakes.
	Feasibility float64 `json:"feasibility"`
	// hoursPerWeek x feasibility. The backlog is sorted by it.
	Score     float64   `json:"score"`
	AgentID   *string   `json:"agentId,omitempty"`
	Agent     *Agent    `json:"agent,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type OpportunityPayload struct {
	Opportunity *Opportunity `json:"opportunity,omitempty"`
	UserErrors  []*UserError `json:"userErrors"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PendingToolCall struct {
	CallID    string          `json:"callId"`
	Tool      *Tool           `json:"tool"`
	Arguments json.RawMessage `json:"arguments"`
}

type Query struct {
}

type Review struct {
	Verdict  Verdict   `json:"verdict"`
	Reviewer string    `json:"reviewer"`
	Note     string    `json:"note"`
	At       time.Time `json:"at"`
}

type ReviewRunInput struct {
	RunID   string  `json:"runId"`
	Verdict Verdict `json:"verdict"`
	Note    *string `json:"note,omitempty"`
}

type Run struct {
	ID            string          `json:"id"`
	AgentID       string          `json:"agentId"`
	Agent         *Agent          `json:"agent"`
	Model         *Model          `json:"model"`
	Variant       Variant         `json:"variant"`
	ExperimentID  *string         `json:"experimentId,omitempty"`
	Trigger       RunTrigger      `json:"trigger"`
	Input         json.RawMessage `json:"input"`
	Status        RunStatus       `json:"status"`
	Output        string          `json:"output"`
	FailureReason string          `json:"failureReason"`
	Turns         int             `json:"turns"`
	Usage         *Usage          `json:"usage"`
	Cost          domain.Micros   `json:"cost"`
	// The tool call waiting for a human, when status is AWAITING_APPROVAL.
	PendingToolCall *PendingToolCall `json:"pendingToolCall,omitempty"`
	Steps           []*RunStep       `json:"steps"`
	Review          *Review          `json:"review,omitempty"`
	CreatedAt       time.Time        `json:"createdAt"`
	StartedAt       *time.Time       `json:"startedAt,omitempty"`
	FinishedAt      *time.Time       `json:"finishedAt,omitempty"`
	DurationSeconds *float64         `json:"durationSeconds,omitempty"`
}

type RunConnection struct {
	Edges    []*RunEdge `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type RunEdge struct {
	Cursor string `json:"cursor"`
	Node   *Run   `json:"node"`
}

type RunPayload struct {
	Run        *Run         `json:"run,omitempty"`
	UserErrors []*UserError `json:"userErrors"`
}

type RunStep struct {
	Index     int             `json:"index"`
	Kind      StepKind        `json:"kind"`
	ToolName  *string         `json:"toolName,omitempty"`
	Summary   string          `json:"summary"`
	Detail    json.RawMessage `json:"detail"`
	LatencyMs int             `json:"latencyMs"`
	Cost      domain.Micros   `json:"cost"`
	At        time.Time       `json:"at"`
}

type Scorecard struct {
	WindowDays   int     `json:"windowDays"`
	FinishedRuns int     `json:"finishedRuns"`
	Succeeded    int     `json:"succeeded"`
	Failed       int     `json:"failed"`
	SuccessRate  float64 `json:"successRate"`
	Reviewed     int     `json:"reviewed"`
	// Share of reviewed output that was kept (edited counts half). Null until something was reviewed.
	AcceptanceRate *float64      `json:"acceptanceRate,omitempty"`
	TotalCost      domain.Micros `json:"totalCost"`
	CostPerRun     domain.Micros `json:"costPerRun"`
	HoursSaved     float64       `json:"hoursSaved"`
	ValueDelivered domain.Micros `json:"valueDelivered"`
	// Value delivered minus model spend. Negative means the agent costs more than it saves.
	NetValue           domain.Micros `json:"netValue"`
	AvgDurationSeconds float64       `json:"avgDurationSeconds"`
}

type StartExperimentInput struct {
	AgentID string `json:"agentId"`
	// provider/name of the challenger model.
	Challenger string `json:"challenger"`
	// Share of runs sent to the challenger, 1 to 50.
	TrafficPercent int    `json:"trafficPercent"`
	Hypothesis     string `json:"hypothesis"`
}

type StartRunInput struct {
	// Give agentId or agentSlug.
	AgentID   *string `json:"agentId,omitempty"`
	AgentSlug *string `json:"agentSlug,omitempty"`
	// The task, as a JSON object.
	Input json.RawMessage `json:"input"`
	// Retrying with the same key returns the first run instead of starting another.
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
}

type SubmitOpportunityInput struct {
	Title           string     `json:"title"`
	Problem         string     `json:"problem"`
	Department      Department `json:"department"`
	WeeklyVolume    int        `json:"weeklyVolume"`
	MinutesPerTask  float64    `json:"minutesPerTask"`
	DataSensitivity Level      `json:"dataSensitivity"`
	ErrorCost       Level      `json:"errorCost"`
}

type Tool struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	// Runs pause for a human before this tool executes.
	RequiresApproval bool `json:"requiresApproval"`
	// JSON Schema the arguments must satisfy.
	InputSchema json.RawMessage `json:"inputSchema"`
}

// Omitted fields keep their current value.
type UpdateAgentInput struct {
	ID                 string         `json:"id"`
	ExpectedVersion    int            `json:"expectedVersion"`
	Name               *string        `json:"name,omitempty"`
	Description        *string        `json:"description,omitempty"`
	Department         *Department    `json:"department,omitempty"`
	Owner              *string        `json:"owner,omitempty"`
	Instructions       *string        `json:"instructions,omitempty"`
	Model              *string        `json:"model,omitempty"`
	Tools              []string       `json:"tools,omitempty"`
	Triggers           []string       `json:"triggers,omitempty"`
	MaxSteps           *int           `json:"maxSteps,omitempty"`
	MaxCost            *domain.Micros `json:"maxCost,omitempty"`
	MinutesSavedPerRun *float64       `json:"minutesSavedPerRun,omitempty"`
}

type Usage struct {
	InputTokens       int `json:"inputTokens"`
	CachedInputTokens int `json:"cachedInputTokens"`
	OutputTokens      int `json:"outputTokens"`
}

type UserError struct {
	// Path to the offending input field, e.g. ["input", "tools", "1"]. Empty when not tied to a field.
	Field   []string      `json:"field"`
	Code    UserErrorCode `json:"code"`
	Message string        `json:"message"`
}

type Viewer struct {
	Email string `json:"email"`
}

type AgentStatus string

const (
	AgentStatusDraft     AgentStatus = "DRAFT"
	AgentStatusActive    AgentStatus = "ACTIVE"
	AgentStatusProbation AgentStatus = "PROBATION"
	AgentStatusRetired   AgentStatus = "RETIRED"
)

var AllAgentStatus = []AgentStatus{
	AgentStatusDraft,
	AgentStatusActive,
	AgentStatusProbation,
	AgentStatusRetired,
}

func (e AgentStatus) IsValid() bool {
	switch e {
	case AgentStatusDraft, AgentStatusActive, AgentStatusProbation, AgentStatusRetired:
		return true
	}
	return false
}

func (e AgentStatus) String() string {
	return string(e)
}

func (e *AgentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentStatus", str)
	}
	return nil
}

func (e AgentStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Decision string

const (
	DecisionKeep             Decision = "KEEP"
	DecisionProbation        Decision = "PROBATION"
	DecisionRetire           Decision = "RETIRE"
	DecisionReinstate        Decision = "REINSTATE"
	DecisionInsufficientData Decision = "INSUFFICIENT_DATA"
)

var AllDecision = []Decision{
	DecisionKeep,
	DecisionProbation,
	DecisionRetire,
	DecisionReinstate,
	DecisionInsufficientData,
}

func (e Decision) IsValid() bool {
	switch e {
	case DecisionKeep, DecisionProbation, DecisionRetire, DecisionReinstate, DecisionInsufficientData:
		return true
	}
	return false
}

func (e Decision) String() string {
	return string(e)
}

func (e *Decision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Decision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Decision", str)
	}
	return nil
}

func (e Decision) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Decision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Decision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Department string

const (
	DepartmentPrepress           Department = "PREPRESS"
	DepartmentCustomerExperience Department = "CUSTOMER_EXPERIENCE"
	DepartmentOperations         Department = "OPERATIONS"
	DepartmentMarketing          Department = "MARKETING"
	DepartmentFinance            Department = "FINANCE"
)

var AllDepartment = []Department{
	DepartmentPrepress,
	DepartmentCustomerExperience,
	DepartmentOperations,
	DepartmentMarketing,
	DepartmentFinance,
}

func (e Department) IsValid() bool {
	switch e {
	case DepartmentPrepress, DepartmentCustomerExperience, DepartmentOperations, DepartmentMarketing, DepartmentFinance:
		return true
	}
	return false
}

func (e Department) String() string {
	return string(e)
}

func (e *Department) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Department(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Department", str)
	}
	return nil
}

func (e Department) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Department) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Department) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExperimentStatus string

const (
	ExperimentStatusRunning  ExperimentStatus = "RUNNING"
	ExperimentStatusPromoted ExperimentStatus = "PROMOTED"
	ExperimentStatusRejected ExperimentStatus = "REJECTED"
)

var AllExperimentStatus = []ExperimentStatus{
	ExperimentStatusRunning,
	ExperimentStatusPromoted,
	ExperimentStatusRejected,
}

func (e ExperimentStatus) IsValid() bool {
	switch e {
	case ExperimentStatusRunning, ExperimentStatusPromoted, ExperimentStatusRejected:
		return true
	}
	return false
}

func (e ExperimentStatus) String() string {
	return string(e)
}

func (e *ExperimentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExperimentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExperimentStatus", str)
	}
	return nil
}

func (e ExperimentStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExperimentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExperimentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Level string

const (
	LevelLow    Level = "LOW"
	LevelMedium Level = "MEDIUM"
	LevelHigh   Level = "HIGH"
)

var AllLevel = []Level{
	LevelLow,
	LevelMedium,
	LevelHigh,
}

func (e Level) IsValid() bool {
	switch e {
	case LevelLow, LevelMedium, LevelHigh:
		return true
	}
	return false
}

func (e Level) String() string {
	return string(e)
}

func (e *Level) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Level(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Level", str)
	}
	return nil
}

func (e Level) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Level) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Level) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ModelProvider string

const (
	ModelProviderAnthropic  ModelProvider = "ANTHROPIC"
	ModelProviderOpenai     ModelProvider = "OPENAI"
	ModelProviderXai        ModelProvider = "XAI"
	ModelProviderOpenSource ModelProvider = "OPEN_SOURCE"
	ModelProviderSandbox    ModelProvider = "SANDBOX"
)

var AllModelProvider = []ModelProvider{
	ModelProviderAnthropic,
	ModelProviderOpenai,
	ModelProviderXai,
	ModelProviderOpenSource,
	ModelProviderSandbox,
}

func (e ModelProvider) IsValid() bool {
	switch e {
	case ModelProviderAnthropic, ModelProviderOpenai, ModelProviderXai, ModelProviderOpenSource, ModelProviderSandbox:
		return true
	}
	return false
}

func (e ModelProvider) String() string {
	return string(e)
}

func (e *ModelProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ModelProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ModelProvider", str)
	}
	return nil
}

func (e ModelProvider) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ModelProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ModelProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OpportunityStatus string

const (
	OpportunityStatusSubmitted OpportunityStatus = "SUBMITTED"
	OpportunityStatusApproved  OpportunityStatus = "APPROVED"
	OpportunityStatusShipped   OpportunityStatus = "SHIPPED"
	OpportunityStatusDeclined  OpportunityStatus = "DECLINED"
)

var AllOpportunityStatus = []OpportunityStatus{
	OpportunityStatusSubmitted,
	OpportunityStatusApproved,
	OpportunityStatusShipped,
	OpportunityStatusDeclined,
}

func (e OpportunityStatus) IsValid() bool {
	switch e {
	case OpportunityStatusSubmitted, OpportunityStatusApproved, OpportunityStatusShipped, OpportunityStatusDeclined:
		return true
	}
	return false
}

func (e OpportunityStatus) String() string {
	return string(e)
}

func (e *OpportunityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OpportunityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OpportunityStatus", str)
	}
	return nil
}

func (e OpportunityStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OpportunityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OpportunityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RunStatus string

const (
	RunStatusQueued           RunStatus = "QUEUED"
	RunStatusRunning          RunStatus = "RUNNING"
	RunStatusAwaitingApproval RunStatus = "AWAITING_APPROVAL"
	RunStatusSucceeded        RunStatus = "SUCCEEDED"
	RunStatusFailed           RunStatus = "FAILED"
	RunStatusCancelled        RunStatus = "CANCELLED"
)

var AllRunStatus = []RunStatus{
	RunStatusQueued,
	RunStatusRunning,
	RunStatusAwaitingApproval,
	RunStatusSucceeded,
	RunStatusFailed,
	RunStatusCancelled,
}

func (e RunStatus) IsValid() bool {
	switch e {
	case RunStatusQueued, RunStatusRunning, RunStatusAwaitingApproval, RunStatusSucceeded, RunStatusFailed, RunStatusCancelled:
		return true
	}
	return false
}

func (e RunStatus) String() string {
	return string(e)
}

func (e *RunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RunStatus", str)
	}
	return nil
}

func (e RunStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RunTrigger string

const (
	RunTriggerManual   RunTrigger = "MANUAL"
	RunTriggerEvent    RunTrigger = "EVENT"
	RunTriggerSchedule RunTrigger = "SCHEDULE"
)

var AllRunTrigger = []RunTrigger{
	RunTriggerManual,
	RunTriggerEvent,
	RunTriggerSchedule,
}

func (e RunTrigger) IsValid() bool {
	switch e {
	case RunTriggerManual, RunTriggerEvent, RunTriggerSchedule:
		return true
	}
	return false
}

func (e RunTrigger) String() string {
	return string(e)
}

func (e *RunTrigger) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RunTrigger(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RunTrigger", str)
	}
	return nil
}

func (e RunTrigger) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RunTrigger) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RunTrigger) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StepKind string

const (
	StepKindModelTurn         StepKind = "MODEL_TURN"
	StepKindToolCall          StepKind = "TOOL_CALL"
	StepKindApprovalRequested StepKind = "APPROVAL_REQUESTED"
	StepKindApprovalGranted   StepKind = "APPROVAL_GRANTED"
	StepKindApprovalDenied    StepKind = "APPROVAL_DENIED"
	StepKindCompleted         StepKind = "COMPLETED"
	StepKindFailed            StepKind = "FAILED"
)

var AllStepKind = []StepKind{
	StepKindModelTurn,
	StepKindToolCall,
	StepKindApprovalRequested,
	StepKindApprovalGranted,
	StepKindApprovalDenied,
	StepKindCompleted,
	StepKindFailed,
}

func (e StepKind) IsValid() bool {
	switch e {
	case StepKindModelTurn, StepKindToolCall, StepKindApprovalRequested, StepKindApprovalGranted, StepKindApprovalDenied, StepKindCompleted, StepKindFailed:
		return true
	}
	return false
}

func (e StepKind) String() string {
	return string(e)
}

func (e *StepKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StepKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StepKind", str)
	}
	return nil
}

func (e StepKind) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StepKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StepKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserErrorCode string

const (
	UserErrorCodeRequired          UserErrorCode = "REQUIRED"
	UserErrorCodeTooLong           UserErrorCode = "TOO_LONG"
	UserErrorCodeOutOfRange        UserErrorCode = "OUT_OF_RANGE"
	UserErrorCodeInvalidFormat     UserErrorCode = "INVALID_FORMAT"
	UserErrorCodeInvalidValue      UserErrorCode = "INVALID_VALUE"
	UserErrorCodeNotFound          UserErrorCode = "NOT_FOUND"
	UserErrorCodeConflict          UserErrorCode = "CONFLICT"
	UserErrorCodeInvalidTransition UserErrorCode = "INVALID_TRANSITION"
)

var AllUserErrorCode = []UserErrorCode{
	UserErrorCodeRequired,
	UserErrorCodeTooLong,
	UserErrorCodeOutOfRange,
	UserErrorCodeInvalidFormat,
	UserErrorCodeInvalidValue,
	UserErrorCodeNotFound,
	UserErrorCodeConflict,
	UserErrorCodeInvalidTransition,
}

func (e UserErrorCode) IsValid() bool {
	switch e {
	case UserErrorCodeRequired, UserErrorCodeTooLong, UserErrorCodeOutOfRange, UserErrorCodeInvalidFormat, UserErrorCodeInvalidValue, UserErrorCodeNotFound, UserErrorCodeConflict, UserErrorCodeInvalidTransition:
		return true
	}
	return false
}

func (e UserErrorCode) String() string {
	return string(e)
}

func (e *UserErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserErrorCode", str)
	}
	return nil
}

func (e UserErrorCode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Variant string

const (
	VariantChampion   Variant = "CHAMPION"
	VariantChallenger Variant = "CHALLENGER"
)

var AllVariant = []Variant{
	VariantChampion,
	VariantChallenger,
}

func (e Variant) IsValid() bool {
	switch e {
	case VariantChampion, VariantChallenger:
		return true
	}
	return false
}

func (e Variant) String() string {
	return string(e)
}

func (e *Variant) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Variant(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Variant", str)
	}
	return nil
}

func (e Variant) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Variant) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Variant) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Verdict string

const (
	VerdictAccepted Verdict = "ACCEPTED"
	VerdictEdited   Verdict = "EDITED"
	VerdictRejected Verdict = "REJECTED"
)

var AllVerdict = []Verdict{
	VerdictAccepted,
	VerdictEdited,
	VerdictRejected,
}

func (e Verdict) IsValid() bool {
	switch e {
	case VerdictAccepted, VerdictEdited, VerdictRejected:
		return true
	}
	return false
}

func (e Verdict) String() string {
	return string(e)
}

func (e *Verdict) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Verdict(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Verdict", str)
	}
	return nil
}

func (e Verdict) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Verdict) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Verdict) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
