// Package model holds the GraphQL transport types. Most are generated by
// gqlgen from schema.graphqls; this file adds the custom scalars.
package model

import (
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"strconv"
	"strings"

	"github.com/99designs/gqlgen/graphql"

	"github.com/davidmm07/pressroom/internal/domain"
)

// ScalarError reports a value a custom scalar cannot accept. The error
// presenter maps it to BAD_USER_INPUT.
type ScalarError struct{ msg string }

func (e *ScalarError) Error() string { return e.msg }

func scalarErr(format string, args ...any) error {
	return &ScalarError{msg: fmt.Sprintf(format, args...)}
}

// MarshalJSON writes raw JSON through unchanged.
func MarshalJSON(v json.RawMessage) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		if len(v) == 0 {
			_, _ = io.WriteString(w, "null")
			return
		}
		_, _ = w.Write(v)
	})
}

// UnmarshalJSON accepts any JSON value from variables or literals.
func UnmarshalJSON(v any) (json.RawMessage, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, scalarErr("JSON scalar: %v", err)
	}
	return b, nil
}

// MarshalUSD writes micros as a quoted decimal string.
func MarshalUSD(m domain.Micros) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = io.WriteString(w, strconv.Quote(m.String()))
	})
}

// UnmarshalUSD accepts "1.25" or 1.25 and rejects more than six decimals, so
// no value is silently rounded on the way in.
func UnmarshalUSD(v any) (domain.Micros, error) {
	var s string
	switch x := v.(type) {
	case string:
		s = strings.TrimSpace(x)
	case json.Number:
		s = x.String()
	case int64:
		s = strconv.FormatInt(x, 10)
	case int:
		s = strconv.Itoa(x)
	case float64:
		s = strconv.FormatFloat(x, 'f', -1, 64)
	default:
		return 0, scalarErr("USD must be a decimal string such as \"1.25\"")
	}
	r, ok := new(big.Rat).SetString(s)
	if !ok {
		return 0, scalarErr("USD: %q is not a decimal number", s)
	}
	micros := new(big.Rat).Mul(r, big.NewRat(1_000_000, 1))
	if !micros.IsInt() {
		return 0, scalarErr("USD: %q has more than six decimal places", s)
	}
	if !micros.Num().IsInt64() {
		return 0, scalarErr("USD: %q is out of range", s)
	}
	return domain.Micros(micros.Num().Int64()), nil
}
