package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"strings"

	"github.com/davidmm07/pressroom/internal/adapter/graphql/generated"
	"github.com/davidmm07/pressroom/internal/adapter/graphql/model"
	"github.com/davidmm07/pressroom/internal/app"
	"github.com/davidmm07/pressroom/internal/domain"
	"github.com/davidmm07/pressroom/internal/platform/auth"
	"github.com/davidmm07/pressroom/internal/port"
)

// Scorecard is the resolver for the scorecard field.
func (r *agentResolver) Scorecard(ctx context.Context, obj *model.Agent, windowDays *int) (*model.Scorecard, error) {
	card, err := r.loadersFrom(ctx).scorecard.Load(ctx, scorecardKey{AgentID: domain.ID(obj.ID), WindowDays: deref(windowDays, 30)})
	if err != nil {
		return nil, err
	}
	return toScorecard(card), nil
}

// Runs is the resolver for the runs field.
func (r *agentResolver) Runs(ctx context.Context, obj *model.Agent, status []model.RunStatus, first *int, after *string) (*model.RunConnection, error) {
	return r.runConnection(ctx, domain.ID(obj.ID), status, first, after)
}

// ActiveExperiment is the resolver for the activeExperiment field.
func (r *agentResolver) ActiveExperiment(ctx context.Context, obj *model.Agent) (*model.Experiment, error) {
	exp, err := r.Experiments.Running(ctx, domain.ID(obj.ID))
	if err != nil || exp == nil {
		return nil, err
	}
	return toExperiment(exp), nil
}

// Evaluations is the resolver for the evaluations field.
func (r *agentResolver) Evaluations(ctx context.Context, obj *model.Agent, last *int) ([]*model.Evaluation, error) {
	evals, err := r.Evaluator.History(ctx, domain.ID(obj.ID), deref(last, 5))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Evaluation, len(evals))
	for i, e := range evals {
		out[i] = toEvaluation(e)
	}
	return out, nil
}

// Agent is the resolver for the agent field.
func (r *evaluationResolver) Agent(ctx context.Context, obj *model.Evaluation) (*model.Agent, error) {
	a, err := r.loadersFrom(ctx).agent.Load(ctx, domain.ID(obj.AgentID))
	if err != nil {
		return nil, err
	}
	return r.toAgent(a), nil
}

// Agent is the resolver for the agent field.
func (r *experimentResolver) Agent(ctx context.Context, obj *model.Experiment) (*model.Agent, error) {
	a, err := r.loadersFrom(ctx).agent.Load(ctx, domain.ID(obj.AgentID))
	if err != nil {
		return nil, err
	}
	return r.toAgent(a), nil
}

// ChampionScorecard is the resolver for the championScorecard field.
func (r *experimentResolver) ChampionScorecard(ctx context.Context, obj *model.Experiment) (*model.Scorecard, error) {
	champion, _, err := r.armScorecards(ctx, obj.ID)
	return champion, err
}

// ChallengerScorecard is the resolver for the challengerScorecard field.
func (r *experimentResolver) ChallengerScorecard(ctx context.Context, obj *model.Experiment) (*model.Scorecard, error) {
	_, challenger, err := r.armScorecards(ctx, obj.ID)
	return challenger, err
}

// CreateAgent is the resolver for the createAgent field.
func (r *mutationResolver) CreateAgent(ctx context.Context, input model.CreateAgentInput) (*model.AgentPayload, error) {
	ref, err := domain.ParseModelRef(input.Model)
	if err != nil {
		return &model.AgentPayload{UserErrors: []*model.UserError{modelFieldError(err)}}, nil
	}
	agent, err := r.Agents.Create(ctx, domain.AgentSpec{
		Slug: strings.TrimSpace(input.Slug), Name: strings.TrimSpace(input.Name), Description: deref(input.Description, ""),
		Department: domain.Department(input.Department), Owner: strings.TrimSpace(input.Owner), Instructions: input.Instructions,
		Model: ref, Tools: input.Tools, Triggers: input.Triggers,
		Budget:             domain.Budget{MaxSteps: input.MaxSteps, MaxCost: input.MaxCost},
		MinutesSavedPerRun: input.MinutesSavedPerRun,
	})
	if err != nil {
		errs, err := userErrors(err, "input", agentInputFields)
		return &model.AgentPayload{UserErrors: errs}, err
	}
	return &model.AgentPayload{Agent: r.toAgent(agent), UserErrors: []*model.UserError{}}, nil
}

// UpdateAgent is the resolver for the updateAgent field.
func (r *mutationResolver) UpdateAgent(ctx context.Context, input model.UpdateAgentInput) (*model.AgentPayload, error) {
	id, err := parseID(input.ID)
	if err != nil {
		return agentFailure(err)
	}
	patch := app.AgentPatch{
		Name: input.Name, Description: input.Description, Owner: input.Owner, Instructions: input.Instructions,
		Tools: input.Tools, Triggers: input.Triggers, MaxSteps: input.MaxSteps, MaxCost: input.MaxCost,
		MinutesSavedPerRun: input.MinutesSavedPerRun,
	}
	if input.Department != nil {
		d := domain.Department(*input.Department)
		patch.Department = &d
	}
	if input.Model != nil {
		ref, err := domain.ParseModelRef(*input.Model)
		if err != nil {
			return &model.AgentPayload{UserErrors: []*model.UserError{modelFieldError(err)}}, nil
		}
		patch.Model = &ref
	}
	agent, err := r.Agents.Update(ctx, id, input.ExpectedVersion, patch)
	if err != nil {
		errs, err := userErrors(err, "input", agentInputFields)
		return &model.AgentPayload{UserErrors: errs}, err
	}
	return &model.AgentPayload{Agent: r.toAgent(agent), UserErrors: []*model.UserError{}}, nil
}

// ActivateAgent is the resolver for the activateAgent field.
func (r *mutationResolver) ActivateAgent(ctx context.Context, id string) (*model.AgentPayload, error) {
	agentID, err := parseID(id)
	if err != nil {
		return agentFailure(err)
	}
	agent, err := r.Agents.Activate(ctx, agentID)
	if err != nil {
		return agentFailure(err)
	}
	return &model.AgentPayload{Agent: r.toAgent(agent), UserErrors: []*model.UserError{}}, nil
}

// RetireAgent is the resolver for the retireAgent field.
func (r *mutationResolver) RetireAgent(ctx context.Context, id string, reason string) (*model.AgentPayload, error) {
	agentID, err := parseID(id)
	if err != nil {
		return agentFailure(err)
	}
	agent, err := r.Agents.Retire(ctx, agentID, strings.TrimSpace(reason))
	if err != nil {
		return agentFailure(err)
	}
	return &model.AgentPayload{Agent: r.toAgent(agent), UserErrors: []*model.UserError{}}, nil
}

// StartRun is the resolver for the startRun field.
func (r *mutationResolver) StartRun(ctx context.Context, input model.StartRunInput) (*model.RunPayload, error) {
	in := app.StartRunInput{
		AgentSlug: deref(input.AgentSlug, ""), Input: input.Input, Trigger: domain.TriggerManual,
		IdempotencyKey: deref(input.IdempotencyKey, ""),
	}
	if input.AgentID != nil {
		id, err := parseID(*input.AgentID)
		if err != nil {
			return runFailure(err)
		}
		in.AgentID = id
	}
	run, err := r.Runs.Start(ctx, in)
	if err != nil {
		return runFailure(err)
	}
	return &model.RunPayload{Run: r.toRun(run), UserErrors: []*model.UserError{}}, nil
}

// ApproveToolCall is the resolver for the approveToolCall field.
func (r *mutationResolver) ApproveToolCall(ctx context.Context, runID string) (*model.RunPayload, error) {
	return r.changeRun(ctx, runID, func(id domain.ID) (*domain.Run, error) {
		return r.Runs.Approve(ctx, id, auth.ActorFrom(ctx))
	})
}

// DenyToolCall is the resolver for the denyToolCall field.
func (r *mutationResolver) DenyToolCall(ctx context.Context, runID string, reason string) (*model.RunPayload, error) {
	return r.changeRun(ctx, runID, func(id domain.ID) (*domain.Run, error) {
		return r.Runs.Deny(ctx, id, auth.ActorFrom(ctx), reason)
	})
}

// ReviewRun is the resolver for the reviewRun field.
func (r *mutationResolver) ReviewRun(ctx context.Context, input model.ReviewRunInput) (*model.RunPayload, error) {
	return r.changeRun(ctx, input.RunID, func(id domain.ID) (*domain.Run, error) {
		return r.Runs.Review(ctx, id, domain.Verdict(input.Verdict), auth.ActorFrom(ctx), deref(input.Note, ""))
	})
}

// CancelRun is the resolver for the cancelRun field.
func (r *mutationResolver) CancelRun(ctx context.Context, runID string) (*model.RunPayload, error) {
	return r.changeRun(ctx, runID, func(id domain.ID) (*domain.Run, error) { return r.Runs.Cancel(ctx, id) })
}

// StartExperiment is the resolver for the startExperiment field.
func (r *mutationResolver) StartExperiment(ctx context.Context, input model.StartExperimentInput) (*model.ExperimentPayload, error) {
	agentID, err := parseID(input.AgentID)
	if err != nil {
		return experimentFailure(err)
	}
	names := fieldNames{"model": "challenger", "provider": "challenger", "name": "challenger",
		"challenger.provider": "challenger", "challenger.name": "challenger"}
	challenger, err := domain.ParseModelRef(input.Challenger)
	if err != nil {
		errs, err := userErrors(err, "input", names)
		return &model.ExperimentPayload{UserErrors: errs}, err
	}
	exp, err := r.Experiments.Start(ctx, app.StartExperimentInput{
		AgentID: agentID, Challenger: challenger, TrafficPercent: input.TrafficPercent, Hypothesis: strings.TrimSpace(input.Hypothesis),
	})
	if err != nil {
		errs, err := userErrors(err, "input", names)
		return &model.ExperimentPayload{UserErrors: errs}, err
	}
	return &model.ExperimentPayload{Experiment: toExperiment(exp), UserErrors: []*model.UserError{}}, nil
}

// ConcludeExperiment is the resolver for the concludeExperiment field.
func (r *mutationResolver) ConcludeExperiment(ctx context.Context, id string, force *bool) (*model.ExperimentPayload, error) {
	expID, err := parseID(id)
	if err != nil {
		return experimentFailure(err)
	}
	exp, err := r.Experiments.Conclude(ctx, expID, deref(force, false))
	if err != nil {
		return experimentFailure(err)
	}
	return &model.ExperimentPayload{Experiment: toExperiment(exp), UserErrors: []*model.UserError{}}, nil
}

// EvaluateCrew is the resolver for the evaluateCrew field.
func (r *mutationResolver) EvaluateCrew(ctx context.Context) (*model.EvaluateCrewPayload, error) {
	evals, err := r.Evaluator.EvaluateCrew(ctx)
	if err != nil {
		errs, err := userErrors(err, "", nil)
		return &model.EvaluateCrewPayload{Evaluations: []*model.Evaluation{}, UserErrors: errs}, err
	}
	out := make([]*model.Evaluation, len(evals))
	for i, e := range evals {
		out[i] = toEvaluation(e)
	}
	return &model.EvaluateCrewPayload{Evaluations: out, UserErrors: []*model.UserError{}}, nil
}

// SubmitOpportunity is the resolver for the submitOpportunity field.
func (r *mutationResolver) SubmitOpportunity(ctx context.Context, input model.SubmitOpportunityInput) (*model.OpportunityPayload, error) {
	o, err := r.Opportunities.Submit(ctx, domain.OpportunityInput{
		Title: strings.TrimSpace(input.Title), Problem: strings.TrimSpace(input.Problem),
		Department: domain.Department(input.Department), SubmittedBy: auth.ActorFrom(ctx),
		WeeklyVolume: input.WeeklyVolume, MinutesPerTask: input.MinutesPerTask,
		DataSensitivity: domain.Level(input.DataSensitivity), ErrorCost: domain.Level(input.ErrorCost),
	})
	if err != nil {
		errs, err := userErrors(err, "input", nil)
		return &model.OpportunityPayload{UserErrors: errs}, err
	}
	return &model.OpportunityPayload{Opportunity: toOpportunity(o), UserErrors: []*model.UserError{}}, nil
}

// MoveOpportunity is the resolver for the moveOpportunity field.
func (r *mutationResolver) MoveOpportunity(ctx context.Context, id string, status model.OpportunityStatus, agentID *string) (*model.OpportunityPayload, error) {
	oppID, err := parseID(id)
	var linked domain.ID
	if err == nil && agentID != nil {
		linked, err = parseID(*agentID)
	}
	if err == nil {
		var o *domain.Opportunity
		if o, err = r.Opportunities.Move(ctx, oppID, domain.OpportunityStatus(status), linked); err == nil {
			return &model.OpportunityPayload{Opportunity: toOpportunity(o), UserErrors: []*model.UserError{}}, nil
		}
	}
	errs, err := userErrors(err, "", nil)
	return &model.OpportunityPayload{UserErrors: errs}, err
}

// Agent is the resolver for the agent field.
func (r *opportunityResolver) Agent(ctx context.Context, obj *model.Opportunity) (*model.Agent, error) {
	if obj.AgentID == nil {
		return nil, nil
	}
	a, err := r.loadersFrom(ctx).agent.Load(ctx, domain.ID(*obj.AgentID))
	if err != nil {
		return nil, nilIfNotFound(err)
	}
	return r.toAgent(a), nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Viewer, error) {
	return &model.Viewer{Email: auth.ActorFrom(ctx)}, nil
}

// Crew is the resolver for the crew field.
func (r *queryResolver) Crew(ctx context.Context) (*model.CrewSummary, error) {
	agents, err := r.Resolver.Agents.List(ctx, port.AgentFilter{})
	if err != nil {
		return nil, err
	}
	summary := &model.CrewSummary{}
	for _, a := range agents {
		switch a.Status {
		case domain.AgentActive:
			summary.ActiveAgents++
		case domain.AgentProbation:
			summary.OnProbation++
		case domain.AgentRetired:
			summary.Retired++
		}
	}
	if len(agents) > 0 {
		month, err := r.Evaluator.Scorecards(ctx, agents, 30)
		if err != nil {
			return nil, err
		}
		week, err := r.Evaluator.Scorecards(ctx, agents, 7)
		if err != nil {
			return nil, err
		}
		for _, a := range agents {
			summary.HoursSavedLast30Days += month[a.ID].HoursSaved()
			summary.SpendLast30Days += month[a.ID].Cost
			summary.NetValueLast30Days += month[a.ID].NetValue()
			summary.RunsLast7Days += week[a.ID].Finished
		}
	}
	waiting, _, err := r.Resolver.Runs.List(ctx, port.RunFilter{Status: []domain.RunStatus{domain.RunAwaitingApproval}}, port.Page{First: 100})
	if err != nil {
		return nil, err
	}
	summary.AwaitingApproval = len(waiting)
	return summary, nil
}

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context, status []model.AgentStatus, department *model.Department) ([]*model.Agent, error) {
	f := port.AgentFilter{}
	for _, s := range status {
		f.Status = append(f.Status, domain.AgentStatus(s))
	}
	if department != nil {
		f.Department = domain.Department(*department)
	}
	agents, err := r.Resolver.Agents.List(ctx, f)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Agent, len(agents))
	for i, a := range agents {
		out[i] = r.toAgent(a)
	}
	return out, nil
}

// Agent is the resolver for the agent field.
func (r *queryResolver) Agent(ctx context.Context, id *string, slug *string) (*model.Agent, error) {
	var (
		agent *domain.Agent
		err   error
	)
	switch {
	case id != nil:
		var agentID domain.ID
		if agentID, err = parseID(*id); err == nil {
			agent, err = r.Resolver.Agents.Get(ctx, agentID)
		}
	case slug != nil:
		agent, err = r.Resolver.Agents.GetBySlug(ctx, *slug)
	default:
		return nil, domain.NewValidationError("id", domain.CodeRequired, "give an id or a slug")
	}
	if err != nil {
		return nil, nilIfNotFound(err)
	}
	return r.toAgent(agent), nil
}

// Run is the resolver for the run field.
func (r *queryResolver) Run(ctx context.Context, id string) (*model.Run, error) {
	runID, err := parseID(id)
	if err != nil {
		return nil, nil
	}
	run, err := r.loadersFrom(ctx).run.Load(ctx, runID)
	if err != nil {
		return nil, nilIfNotFound(err)
	}
	return r.toRun(run), nil
}

// Runs is the resolver for the runs field.
func (r *queryResolver) Runs(ctx context.Context, agentID *string, status []model.RunStatus, first *int, after *string) (*model.RunConnection, error) {
	var id domain.ID
	if agentID != nil {
		var err error
		if id, err = parseID(*agentID); err != nil {
			return r.toConnection(nil, false), nil
		}
	}
	return r.runConnection(ctx, id, status, first, after)
}

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context) ([]*model.Tool, error) {
	specs := r.Resolver.Tools.Catalog()
	out := make([]*model.Tool, len(specs))
	for i, s := range specs {
		out[i] = r.toTool(s)
	}
	return out, nil
}

// Models is the resolver for the models field.
func (r *queryResolver) Models(ctx context.Context) ([]*model.ModelOption, error) {
	infos := r.Resolver.Models.Models()
	out := make([]*model.ModelOption, len(infos))
	for i, m := range infos {
		out[i] = &model.ModelOption{
			Model: toModelRef(m.Ref), Label: m.Label, Available: m.Available,
			InputPerMTok: m.Price.InputPerMTok, OutputPerMTok: m.Price.OutputPerMTok,
		}
	}
	return out, nil
}

// Experiments is the resolver for the experiments field.
func (r *queryResolver) Experiments(ctx context.Context, agentID *string, status *model.ExperimentStatus) ([]*model.Experiment, error) {
	var id domain.ID
	if agentID != nil {
		var err error
		if id, err = parseID(*agentID); err != nil {
			return []*model.Experiment{}, nil
		}
	}
	var st domain.ExperimentStatus
	if status != nil {
		st = domain.ExperimentStatus(*status)
	}
	exps, err := r.Resolver.Experiments.List(ctx, id, st)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Experiment, len(exps))
	for i, e := range exps {
		out[i] = toExperiment(e)
	}
	return out, nil
}

// Opportunities is the resolver for the opportunities field.
func (r *queryResolver) Opportunities(ctx context.Context, status *model.OpportunityStatus, department *model.Department) ([]*model.Opportunity, error) {
	var st domain.OpportunityStatus
	if status != nil {
		st = domain.OpportunityStatus(*status)
	}
	var dept domain.Department
	if department != nil {
		dept = domain.Department(*department)
	}
	list, err := r.Resolver.Opportunities.Backlog(ctx, st, dept)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Opportunity, len(list))
	for i, o := range list {
		out[i] = toOpportunity(o)
	}
	return out, nil
}

// Agent is the resolver for the agent field.
func (r *runResolver) Agent(ctx context.Context, obj *model.Run) (*model.Agent, error) {
	a, err := r.loadersFrom(ctx).agent.Load(ctx, domain.ID(obj.AgentID))
	if err != nil {
		return nil, err
	}
	return r.toAgent(a), nil
}

// Steps is the resolver for the steps field.
func (r *runResolver) Steps(ctx context.Context, obj *model.Run) ([]*model.RunStep, error) {
	run, err := r.loadersFrom(ctx).run.Load(ctx, domain.ID(obj.ID))
	if err != nil {
		return nil, err
	}
	out := make([]*model.RunStep, len(run.Steps))
	for i, s := range run.Steps {
		out[i] = toStep(s)
	}
	return out, nil
}

// Agent returns generated.AgentResolver implementation.
func (r *Resolver) Agent() generated.AgentResolver { return &agentResolver{r} }

// Evaluation returns generated.EvaluationResolver implementation.
func (r *Resolver) Evaluation() generated.EvaluationResolver { return &evaluationResolver{r} }

// Experiment returns generated.ExperimentResolver implementation.
func (r *Resolver) Experiment() generated.ExperimentResolver { return &experimentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Opportunity returns generated.OpportunityResolver implementation.
func (r *Resolver) Opportunity() generated.OpportunityResolver { return &opportunityResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Run returns generated.RunResolver implementation.
func (r *Resolver) Run() generated.RunResolver { return &runResolver{r} }

type (
	agentResolver       struct{ *Resolver }
	evaluationResolver  struct{ *Resolver }
	experimentResolver  struct{ *Resolver }
	mutationResolver    struct{ *Resolver }
	opportunityResolver struct{ *Resolver }
	queryResolver       struct{ *Resolver }
	runResolver         struct{ *Resolver }
)
